import mongoose from 'mongoose';

// Define the schema for the facture_steg model
const factureStegSchema = new mongoose.Schema(
  {
    numfacture: String,
    mois: String,
    annee: Number,
    souscrite_jour: Number,
    souscrite_pointete: Number,
    souscrite_soir: Number,
    souscrite_pointhiver: Number,
    souscrite_reduite: Number,
    maxiappelee_jour: Number,
    maxiappelee_pointete: Number,
    maxiappelee_soir: Number,
    maxiappelee_pointehiver: Number,
    maxiappelee_reduite: Number,
    depassement_puissance_jour: Number,
    depassement_puissance_pointete: Number,
    depassement_puissance_soir: Number,
    depassement_puissance_hiver: Number,
    depassement_puissance_reduite: Number,
    puissanceinstalle: Number,
    cosphi: Number,
    coefk: Number,
    consommation_jour: Number,
    consommation_pointe: Number,
    consommation_soir: Number,
    consommation_nuit: Number,
    consommation_total: Number,
    prixkwh_jour: Number,
    prixkwh_pointe: Number,
    prixkwh_soir: Number,
    prixkwh_nuit: Number,
    montant_jour: Number,
    montant_pointe: Number,
    montant_soir: Number,
    montant_nuit: Number,
    montant_total: Number,
    bonfincation: Number,
    penalite: Number,
    totala: Number,
    prime_puissance: Number,
    depassement_puissance: Number,
    location_materiel: Number,
    frais_intervention: Number,
    frais_relance: Number,
    frais_retard: Number,
    totalb: Number,
    tva_consommation: Number,
    tva_redevance: Number,
    contribution_rtt: Number,
    surtaxminicipale: Number,
    totalc: Number,
    avance_consomation: Number,
    neta_payer: Number,
    consommation_cible_mois: Number,
    fichier: String,
    nom_facture: String,
    datefacture: Date,
  },
  { collection: 'facture_steg' }
); // Specify the collection name here

// Create the facture_steg model using the schema
const FactureSteg = mongoose.model('FactureSteg', factureStegSchema);

export default FactureSteg;
